
<?php echo $error ; ?>
<table>
		<form method="POST">
		<tr>
			<td>Login</td>
			<td><input type="text" name="login"/></td>
		</tr>
		
		<tr>
			<td class="white">E-mail</td>
			<td><input type="email" name="email"/></td>
		</tr>
                <tr>
			<td class="white">Password</td>
			<td><input type="password" name="password"/></td>
		</tr>
		<tr>
			<td class="white">Confirm password</td>
			<td><input type="password" name="password2"/></td>
		</tr>
                <tr>
                    <td><input type="submit" name="inscription" value="envoyer"/></td>
                </tr>
		
		
</form>

</table>
