<h1>template 3</h1>
<a href="template">template</a><a href="template2">template2</a>
<div class="container_temp3">



			<header class="header_temp3">
				    <div class="bordure">
				    </div> 
				<figure class="figure_temp3">
				    <img class="logo_temp3" src="logo.png" alt="iconne_" />
				</figure>
				<nav>
					<ul class="ul_temp3">
						<li class="li_temp3"><a href="#">Location</a>
						</li>
						<li class="li_temp3"><a href="#">AboutUs</a>
						</li>
						<li class="li_temp3"><a href="#">CONTACT</a>
						</li>
                              </ul>
				</nav>
				    <div class="bordure2">
				    </div> 

			</header>

			<article class="welcome">
				<p class="h3">Welcome to Fish & Chips !</p>
				<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod
				tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam,
				quis nostrud 
			    </p>
			    <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod
				tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam,
				quis nostrud exercitation 
			    </p>
			    <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod
				tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam,
				quis nostrud exercitation 
				
			    </p>
			    <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod
				tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam,
				quis nostrud 
				
			    </p>
            </article>

            <div class="azerty">
            	<article class="today">
            		<div class="titre">
            		    <h2 id="today_s">Today's</h2>
	            		<p class="special_r">Special Recipes</p>
                    </div>
            		<section class="section_temp3">
            			<p class="titre"> <i class="fa fa-tint"></i>
Le crusty fish <i class="fa fa-tint"></i>
                              </p>
            			<img class="crusty" src="recipe1.jpg" alt="crusty" />
            			<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod
            			tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam,
            			quis nostrud exercitation ullamco laboris
            		    </p>
            		    <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod
            			tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam,
            			quis nostrud exercitation ullamco laboris
            		    </p>
            		    <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod
            			tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam,
            			quis nostrud exercitation ullamco laboris
            		    </p>
            		    <a class="reade_more" href="#">reade more <i class="fa fa-plus-circle"> </i>
                            </a>
            		    
            		    

            		</section>
            		<section class="section_temp3">
            			
                              <p class="titre"> <i class="fa fa-tint"></i>
La mustifish <i class="fa fa-tint"></i>
                              </p> 

            			<img class="mustifish" src="recipe2.jpg" alt="mustifish" />
            			<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod
            			tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam,
            			quis nostrud exercitation ullamco laboris
            		    </p>
            		    <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod
            			tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam,
            			quis nostrud exercitation ullamco laboris
            		    </p>
            		    <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod
            			tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam,
            			quis nostrud exercitation ullamco laboris
            		    </p>
            		    <a class="reade_more" href="#">reade more <i class="fa fa-plus-circle"> </i>
                            </a>

            		    
            		</section>
            	</article>
            	<menu class="menu_temp3">
            		<p class="h5">News </p>
            		<img class="vignette" src="vignette.png" alt="logo" />
            		<h5> <i class="fa fa-comment-o"></i>
               18.01/15</h5>
            	    <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod
            		tempor 
            	    </p>
                      <h5> <i class="fa fa-comment-o"></i>
              18.01/15</h5>
            		<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod
            		tempor  
            	    </p>
            	    <p> <i class="fa fa-comment-o"></i>
              18.01/15</p>
            		<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod
            		tempor  
            	    </p>
            	    <h5> 
              18.01/15</h5>
            		<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod
            		tempor 
            	    </p>
            	    <h5> <i class="fa fa-comment-o"></i>
              18.01/15</h5>
            	    <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod
            		tempor 
            	    </p>

            	</menu>
            </div>


		</div>

